/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.calendar.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EventsAttendees extends org.jooq.impl.TableImpl<com.sonicle.webtop.calendar.jooq.tables.records.EventsAttendeesRecord> {

	private static final long serialVersionUID = 311901132;

	/**
	 * The reference instance of <code>calendar.events_attendees</code>
	 */
	public static final com.sonicle.webtop.calendar.jooq.tables.EventsAttendees EVENTS_ATTENDEES = new com.sonicle.webtop.calendar.jooq.tables.EventsAttendees();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.sonicle.webtop.calendar.jooq.tables.records.EventsAttendeesRecord> getRecordType() {
		return com.sonicle.webtop.calendar.jooq.tables.records.EventsAttendeesRecord.class;
	}

	/**
	 * The column <code>calendar.events_attendees.attendee_id</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.calendar.jooq.tables.records.EventsAttendeesRecord, java.lang.String> ATTENDEE_ID = createField("attendee_id", org.jooq.impl.SQLDataType.VARCHAR.length(36).nullable(false), this, "");

	/**
	 * The column <code>calendar.events_attendees.event_id</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.calendar.jooq.tables.records.EventsAttendeesRecord, java.lang.Integer> EVENT_ID = createField("event_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>calendar.events_attendees.recipient</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.calendar.jooq.tables.records.EventsAttendeesRecord, java.lang.String> RECIPIENT = createField("recipient", org.jooq.impl.SQLDataType.VARCHAR.length(320), this, "");

	/**
	 * The column <code>calendar.events_attendees.recipient_role</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.calendar.jooq.tables.records.EventsAttendeesRecord, java.lang.String> RECIPIENT_ROLE = createField("recipient_role", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "");

	/**
	 * The column <code>calendar.events_attendees.response_status</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.calendar.jooq.tables.records.EventsAttendeesRecord, java.lang.String> RESPONSE_STATUS = createField("response_status", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "");

	/**
	 * The column <code>calendar.events_attendees.notify</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.calendar.jooq.tables.records.EventsAttendeesRecord, java.lang.Boolean> NOTIFY = createField("notify", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

	/**
	 * The column <code>calendar.events_attendees.recipient_type</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.calendar.jooq.tables.records.EventsAttendeesRecord, java.lang.String> RECIPIENT_TYPE = createField("recipient_type", org.jooq.impl.SQLDataType.VARCHAR.length(3), this, "");

	/**
	 * Create a <code>calendar.events_attendees</code> table reference
	 */
	public EventsAttendees() {
		this("events_attendees", null);
	}

	/**
	 * Create an aliased <code>calendar.events_attendees</code> table reference
	 */
	public EventsAttendees(java.lang.String alias) {
		this(alias, com.sonicle.webtop.calendar.jooq.tables.EventsAttendees.EVENTS_ATTENDEES);
	}

	private EventsAttendees(java.lang.String alias, org.jooq.Table<com.sonicle.webtop.calendar.jooq.tables.records.EventsAttendeesRecord> aliased) {
		this(alias, aliased, null);
	}

	private EventsAttendees(java.lang.String alias, org.jooq.Table<com.sonicle.webtop.calendar.jooq.tables.records.EventsAttendeesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.sonicle.webtop.calendar.jooq.Calendar.CALENDAR, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.sonicle.webtop.calendar.jooq.tables.records.EventsAttendeesRecord> getPrimaryKey() {
		return com.sonicle.webtop.calendar.jooq.Keys.EVENTS_PLANNING_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.sonicle.webtop.calendar.jooq.tables.records.EventsAttendeesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.sonicle.webtop.calendar.jooq.tables.records.EventsAttendeesRecord>>asList(com.sonicle.webtop.calendar.jooq.Keys.EVENTS_PLANNING_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.sonicle.webtop.calendar.jooq.tables.EventsAttendees as(java.lang.String alias) {
		return new com.sonicle.webtop.calendar.jooq.tables.EventsAttendees(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.sonicle.webtop.calendar.jooq.tables.EventsAttendees rename(java.lang.String name) {
		return new com.sonicle.webtop.calendar.jooq.tables.EventsAttendees(name, null);
	}
}
