/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.calendar.jooq;

/**
 * Convenience access to all tables in calendar
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table calendar.calendar_props
	 */
	public static final com.sonicle.webtop.calendar.jooq.tables.CalendarProps CALENDAR_PROPS = com.sonicle.webtop.calendar.jooq.tables.CalendarProps.CALENDAR_PROPS;

	/**
	 * The table calendar.calendars
	 */
	public static final com.sonicle.webtop.calendar.jooq.tables.Calendars CALENDARS = com.sonicle.webtop.calendar.jooq.tables.Calendars.CALENDARS;

	/**
	 * The table calendar.events
	 */
	public static final com.sonicle.webtop.calendar.jooq.tables.Events EVENTS = com.sonicle.webtop.calendar.jooq.tables.Events.EVENTS;

	/**
	 * The table calendar.events_attendees
	 */
	public static final com.sonicle.webtop.calendar.jooq.tables.EventsAttendees EVENTS_ATTENDEES = com.sonicle.webtop.calendar.jooq.tables.EventsAttendees.EVENTS_ATTENDEES;

	/**
	 * The table calendar.recurrences
	 */
	public static final com.sonicle.webtop.calendar.jooq.tables.Recurrences RECURRENCES = com.sonicle.webtop.calendar.jooq.tables.Recurrences.RECURRENCES;

	/**
	 * The table calendar.recurrences_broken
	 */
	public static final com.sonicle.webtop.calendar.jooq.tables.RecurrencesBroken RECURRENCES_BROKEN = com.sonicle.webtop.calendar.jooq.tables.RecurrencesBroken.RECURRENCES_BROKEN;
}
